// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wissance.Pacman.Data;

#nullable disable

namespace Wissance.Pacman.Data.Sqlite.Migrations
{
    [DbContext(typeof(PacmanDbContext))]
    partial class PacmanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("PackagePackageOwner", b =>
                {
                    b.Property<Guid>("OwnersId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.HasKey("OwnersId", "PackageId");

                    b.HasIndex("PackageId");

                    b.ToTable("packages_package_owners", (string)null);
                });

            modelBuilder.Entity("PackageVersionTag", b =>
                {
                    b.Property<Guid>("PackageVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("PackageVersionId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("package_version_tags", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.Localization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("localizations", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.LocalizationString", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalizationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalizationId");

                    b.ToTable("localization_strings", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset?>("DeprecatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeprecatedAt")
                        .HasDatabaseName("ix_packages_deprecated_at");

                    b.HasIndex("IsAvailable")
                        .HasDatabaseName("ix_packages_is_available");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_packages_name");

                    b.ToTable("packages", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.PackageDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaxVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("MinVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageRepo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PackageVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetFrameworkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageVersionId");

                    b.HasIndex("TargetFrameworkId");

                    b.ToTable("package_dependencies", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.PackageOwner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsOrganization")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("package_owners", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.PackageVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsListed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("LicenseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageHashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("TEXT");

                    b.Property<long>("PackageSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PackageVersionStatsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RepositoryType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsListed")
                        .HasDatabaseName("ix_package_versions_is_listed");

                    b.HasIndex("PackageId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_package_versions_package_id_version");

                    b.ToTable("package_versions", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.PackageVersionStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("Downloads")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("PackageVersionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackageVersionId")
                        .IsUnique();

                    b.ToTable("package_version_stats", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.ResourceMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.ToTable("resources", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.TargetFramework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("target_frameworks", (string)null);
                });

            modelBuilder.Entity("PackagePackageOwner", b =>
                {
                    b.HasOne("Wissance.Pacman.Data.Entities.PackageOwner", null)
                        .WithMany()
                        .HasForeignKey("OwnersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wissance.Pacman.Data.Entities.Package", null)
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackageVersionTag", b =>
                {
                    b.HasOne("Wissance.Pacman.Data.Entities.PackageVersion", null)
                        .WithMany()
                        .HasForeignKey("PackageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Wissance.Pacman.Data.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.LocalizationString", b =>
                {
                    b.HasOne("Wissance.Pacman.Data.Entities.Localization", "Loc")
                        .WithMany("Localizations")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loc");
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.PackageDependency", b =>
                {
                    b.HasOne("Wissance.Pacman.Data.Entities.PackageVersion", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("PackageVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Wissance.Pacman.Data.Entities.TargetFramework", "Framework")
                        .WithMany()
                        .HasForeignKey("TargetFrameworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.PackageVersion", b =>
                {
                    b.HasOne("Wissance.Pacman.Data.Entities.Package", "Package")
                        .WithMany("Versions")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.PackageVersionStats", b =>
                {
                    b.HasOne("Wissance.Pacman.Data.Entities.PackageVersion", "PackageVersion")
                        .WithOne("Stats")
                        .HasForeignKey("Wissance.Pacman.Data.Entities.PackageVersionStats", "PackageVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PackageVersion");
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.ResourceMetadata", b =>
                {
                    b.HasOne("Wissance.Pacman.Data.Entities.Localization", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.Localization", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.Package", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Wissance.Pacman.Data.Entities.PackageVersion", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Stats")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
