<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0"/>
        <PackageReference Include="Wissance.WebApiToolkit.Core" Version="5.3.0" />
        <PackageReference Include="Wissance.WebApiToolkit.Ef" Version="5.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Wissance.Pacman.Data\Wissance.Pacman.Data.csproj" />
      <ProjectReference Include="..\Wissance.Pacman.Dto\Wissance.Pacman.Dto.csproj" />
    </ItemGroup>

</Project>
